version: '3'

volumes:
  rabbitmq_data:

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - default

  maildev:
    image: maildev/maildev
    restart: always
    environment:
      TZ: Europe/Lisbon
      MAILDEV_WEB_PORT: 1080
      MAILDEV_SMTP_PORT: 1025
      MAILDEV_OUTGOING_USER: your_username
      MAILDEV_OUTGOING_PASS: your_password
    ports:
      - "8080:1080"
      - "8025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"    
    networks:
      - default

  broker-emiter:
    build: ./broker-emiter
    restart: always
    environment:
      RABBIT_SERVER: rabbitmq      
    ports:
      - 5000:5000
    networks:
      - default

  broker-consumer:
    restart: always
    build: ./broker-consumer
    environment:
      RABBIT_SERVER: rabbitmq
      MAIL_SERVER: maildev
    networks:
      - default
